// Vercel serverless endpoint for BOAT COMMAND JARVIS v0.33.7.
// Secrets stay server-side. Conversation is primary; tools remain allow-listed.
import {ALLOWED_ORIGIN,authorized,cors,scrub} from '../../lib/jarvis-security.js';

const SYSTEM=`You are JARVIS inside BOAT COMMAND, dedicated to Gamagori. Speak natural, context-sensitive Japanese like an excellent personal AI partner, not a command parser. Understand short continuations from conversation context. Use tools only when current app state, an app action, GitHub status, or development work is actually required. Never claim an action completed until its tool output confirms it. The main prediction is PRE-RACE only: never use exhibition, same-day results, finish order, odds, payouts, or future information. Never rewrite HARD LOCK predictions. Never mutate predictions, results, payouts, settlement, or bankroll through conversation. Development work must stay on SHADOW or the dedicated development branch and must never auto-promote to LIVE/main. Write combinations as 1-2-3.`;
const TOOLS=[
 {type:'function',name:'app_status',description:'Read the current BOAT COMMAND state when needed.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'github_status',description:'Read current BOAT COMMAND GitHub main status without changing code.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'open_view',description:'Navigate inside BOAT COMMAND.',parameters:{type:'object',properties:{view:{type:'string',enum:['HOME','LIVE','REPLAY','SETTINGS']}},required:['view'],additionalProperties:false},strict:true},
 {type:'function',name:'open_race',description:'Open a race from 1R through 12R.',parameters:{type:'object',properties:{race:{type:'integer',minimum:1,maximum:12}},required:['race'],additionalProperties:false},strict:true},
 {type:'function',name:'refresh_live',description:'Refresh current LIVE source data without changing locked predictions.',parameters:{type:'object',properties:{},additionalProperties:false},strict:true},
 {type:'function',name:'queue_development',description:'Queue a SHADOW development request. Queued is not completed.',parameters:{type:'object',properties:{request:{type:'string',maxLength:4000}},required:['request'],additionalProperties:false},strict:true}
];
export function textFromResponse(data){if(typeof data?.output_text==='string')return data.output_text.trim();return(Array.isArray(data?.output)?data.output:[]).flatMap(x=>Array.isArray(x?.content)?x.content:[]).map(x=>x?.text||'').join('').trim()}
export function toolCalls(data){return(Array.isArray(data?.output)?data.output:[]).filter(x=>x?.type==='function_call').map(x=>{let args={};try{args=JSON.parse(x.arguments||'{}')}catch{}return{call_id:String(x.call_id||x.id||'').slice(0,120),name:String(x.name||'').slice(0,80),arguments:scrub(args)}})}
export function safeHistory(input){return(Array.isArray(input)?input:[]).slice(-24).filter(x=>x&&['user','assistant'].includes(x.role)).map(x=>({role:x.role,content:String(x.text||'').slice(0,5000)}))}
export function safeToolOutputs(input){return(Array.isArray(input)?input:[]).slice(0,8).filter(x=>x?.call_id).map(x=>({type:'function_call_output',call_id:String(x.call_id).slice(0,120),output:JSON.stringify(scrub(x.output??{}))}))}
async function openai(body){const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify(body)}),data=await r.json();if(!r.ok){const e=new Error('LLM_UPSTREAM_ERROR');e.status=r.status;e.detail=data?.error?.code||null;throw e}return data}
export default async function handler(req,res){
 const origin=cors(req,res);if(req.method==='OPTIONS')return origin===ALLOWED_ORIGIN?res.status(204).end():res.status(403).json({error:'ORIGIN_DENIED'});if(req.method!=='POST')return res.status(405).json({error:'METHOD_NOT_ALLOWED'});if(origin!==ALLOWED_ORIGIN)return res.status(403).json({error:'ORIGIN_DENIED'});if(!process.env.BOAT_COMMAND_ACCESS_TOKEN)return res.status(503).json({error:'ACCESS_GATE_NOT_CONFIGURED'});if(!authorized(req))return res.status(401).json({error:'AUTH_REQUIRED'});if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'JARVIS_LLM_NOT_CONFIGURED'});
 const message=String(req.body?.message||'').normalize('NFKC').trim().slice(0,8000);if(!message)return res.status(400).json({error:'EMPTY_MESSAGE'});const previous=String(req.body?.previous_response_id||'').trim();const previousResponseId=/^resp_[A-Za-z0-9_-]+$/.test(previous)?previous:'';const outputs=safeToolOutputs(req.body?.tool_outputs);
 try{const input=outputs.length?outputs:previousResponseId?[{role:'user',content:message}]:[...safeHistory(req.body?.history),{role:'user',content:message}];const body={model:process.env.JARVIS_OPENAI_MODEL||'gpt-5.6-sol',instructions:SYSTEM,input,tools:TOOLS,tool_choice:outputs.length?'none':'auto',parallel_tool_calls:false,max_output_tokens:1800,reasoning:{effort:'medium'},text:{verbosity:'medium'},store:true};if(previousResponseId)body.previous_response_id=previousResponseId;const data=await openai(body),calls=toolCalls(data),reply=textFromResponse(data);if(calls.length)return res.status(200).json({reply:reply||'',message:reply||'',response_id:data.id||null,model:data.model||body.model,tool_calls:calls});if(!reply)return res.status(502).json({error:'EMPTY_LLM_RESPONSE'});return res.status(200).json({reply,message:reply,response_id:data.id||null,model:data.model||body.model,tool_calls:[]})}catch(e){return res.status(502).json({error:e?.message==='LLM_UPSTREAM_ERROR'?'LLM_UPSTREAM_ERROR':'LLM_REQUEST_FAILED',status:e?.status||null,detail:e?.detail||null})}
}
