// BOAT COMMAND JARVIS -> guarded GitHub executor bridge v0.33.7.
import {authorized,cors} from '../../lib/jarvis-security.js';
const REPO='yoc02119-max/boat-command',API='https://api.github.com',DEV_BRANCH='jarvis-completion-v0336',DEV_ISSUE=2;
function headers(token){return{accept:'application/vnd.github+json',authorization:`Bearer ${token}`,'x-github-api-version':'2022-11-28','user-agent':'boat-command-jarvis'}}
async function gh(token,path,options={}){const r=await fetch(`${API}${path}`,{...options,headers:{...headers(token),...(options.headers||{})}});let data=null;try{data=await r.json()}catch{}return{r,data}}
export function resultFromComments(comments,jobId){for(const c of(Array.isArray(comments)?comments:[]).slice().reverse()){const body=String(c?.body||'');if(!body.includes(jobId))continue;const status=(body.match(/status\s*[:=]\s*(COMPLETED|FAILED|RUNNING)/i)||[])[1]?.toUpperCase();if(!status)continue;return{status,commitSha:(body.match(/(?:commit\s*sha|commit|sha)\s*[:=]\s*([0-9a-f]{7,40})/i)||[])[1]||null,tests:(body.match(/tests?\s*[:=]\s*([^\n]+)/i)||[])[1]?.trim()||null,summary:(body.match(/summary\s*[:=]\s*([^\n]+)/i)||[])[1]?.trim()||'',commentId:c.id||null,commentUrl:c.html_url||null,updatedAt:c.updated_at||c.created_at||null}}return null}
export default async function handler(req,res){
 const origin=cors(req,res);if(req.method==='OPTIONS')return origin?res.status(204).end():res.status(403).json({error:'ORIGIN_DENIED'});if(req.method!=='POST')return res.status(405).json({error:'METHOD_NOT_ALLOWED'});if(!origin)return res.status(403).json({error:'ORIGIN_DENIED'});if(!process.env.BOAT_COMMAND_ACCESS_TOKEN)return res.status(503).json({error:'ACCESS_GATE_NOT_CONFIGURED'});if(!authorized(req))return res.status(401).json({error:'AUTH_REQUIRED'});const token=process.env.JARVIS_GITHUB_EXECUTOR_TOKEN;if(!token)return res.status(503).json({error:'JARVIS_GITHUB_EXECUTOR_NOT_CONFIGURED'});const action=String(req.body?.action||'status');
 try{
  if(action==='status'){const[repoX,branchX]=await Promise.all([gh(token,`/repos/${REPO}`),gh(token,`/repos/${REPO}/branches/main`)]);if(!repoX.r.ok||!branchX.r.ok)return res.status(502).json({error:'GITHUB_UPSTREAM_ERROR',repoStatus:repoX.r.status,branchStatus:branchX.r.status});return res.status(200).json({ok:true,executor:'GITHUB',repository:REPO,branch:'main',sha:branchX.data?.commit?.sha||null,defaultBranch:repoX.data?.default_branch||null,private:Boolean(repoX.data?.private),checkedAt:new Date().toISOString(),mode:'READ_ONLY_STATUS'})}
  if(action==='dispatch_development'){const job=req.body?.job||{},id=String(job.id||'').trim(),request=String(job.request||'').normalize('NFKC').trim().slice(0,4000);if(!/^dev-[A-Za-z0-9.-]+$/.test(id)||!request)return res.status(400).json({error:'INVALID_DEVELOPMENT_JOB'});const forbidden=/(HARD\s*LOCK|払戻|精算|仮想資金|bankroll).*(書き換|変更|削除|解除|増や|減ら)|(当日結果|same.day.result).*(予想|PRE.?RACE)/i;if(forbidden.test(request))return res.status(403).json({error:'PROTECTED_DEVELOPMENT_REQUEST'});const body=[`[JARVIS DEVELOPMENT JOB] ${id}`,'',request,'','Guardrails:','- Gamagori only','- No same-day result/payout/exhibition leak into PRE-RACE','- No direct LIVE prediction overwrite','- No HARD LOCK rewrite','- No result/payout/bankroll rewrite',`- Target branch: ${DEV_BRANCH}`,'- Run tests before reporting completion','- Never auto-promote to main','','Return status, commit SHA, tests, and summary to JARVIS.'].join('\n');const x=await gh(token,`/repos/${REPO}/issues/${DEV_ISSUE}/comments`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({body})});if(!x.r.ok)return res.status(502).json({error:'GITHUB_EXECUTOR_DISPATCH_FAILED',status:x.r.status});return res.status(202).json({ok:true,status:'QUEUED',jobId:id,repository:REPO,branch:DEV_BRANCH,issue:DEV_ISSUE,commentId:x.data?.id||null,commentUrl:x.data?.html_url||null,dispatchedAt:new Date().toISOString(),promotion:'NEVER_AUTO_MAIN'})}
  if(action==='development_result'){const jobId=String(req.body?.jobId||'').trim();if(!/^dev-[A-Za-z0-9.-]+$/.test(jobId))return res.status(400).json({error:'INVALID_JOB_ID'});const x=await gh(token,`/repos/${REPO}/issues/${DEV_ISSUE}/comments?per_page=100`);if(!x.r.ok)return res.status(502).json({error:'GITHUB_EXECUTOR_RESULT_READ_FAILED',status:x.r.status});const result=resultFromComments(x.data,jobId);return res.status(200).json({ok:true,jobId,result:result?{jobId,...result}:null,checkedAt:new Date().toISOString()})}
  return res.status(403).json({error:'ACTION_NOT_ALLOWED'});
 }catch{return res.status(502).json({error:'GITHUB_REQUEST_FAILED'})}
}
